name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check secrets
        run: echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" && echo "DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t mdtrainee/hwl-api:latest .

      - name: Push Docker image to Docker Hub
        run: docker push mdtrainee/hwl-api:latest
